Ofmcc 1635 Lock Supplementary Applications
bcgov/ecc-ofm pull request #149
Opened 2024-04-01 22:30 UTC by jenbeckett

2024-04-01 23:00 UTC, weskubo-cgi requested changes

2024-04-01 23:12 UTC, jenbeckett commented on frontend/src/components/supp-allowances/IndigenousProgrammingAllowance.vue
>  import { INDIG_CHECKBOX_LABELS } from './suppConstants'
done

2024-04-01 23:20 UTC, jenbeckett commented on frontend/src/components/supp-allowances/IndigenousProgrammingAllowance.vue
> +      <template #content>
done

2024-04-01 23:20 UTC, jenbeckett commented on frontend/src/components/ui/AppWarningMessage.vue
> +      <slot name="content"></slot>
done

2024-04-01 23:22 UTC, jenbeckett commented on frontend/src/components/supp-allowances/IndigenousProgrammingAllowance.vue
> +      readonly: false,
removed

2024-04-01 23:22 UTC, jenbeckett commented on frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
> +      <template #content>
done

2024-04-01 23:24 UTC, jenbeckett commented on frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
> +          <router-link to="/account-mgmt/manage-organization">Account Management.</router-link>
done

2024-04-01 23:27 UTC, jenbeckett commented on frontend/src/components/supp-allowances/TransportationAllowance.vue
> +<!-- eslint-disable vue/attribute-hyphenation -->
My linter is constantly giving me errors regarding my attributes not being hyphenated? Even in other files that others have produced. If this is only a 'me' issue, I can try messing around with my linter settings

2024-04-01 23:28 UTC, jenbeckett commented on frontend/src/utils/common.js
> +  return !(applicationStatusCode === STATUS_CODES.DRAFT || applicationStatusCode === STATUS_CODES.ACTION_REQUIRED)
My thinking was it could also be used for regular applications as well? but not sure if that is over complicating it or not.

2024-04-01 23:29 UTC, jenbeckett commented on frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
> +    this.SUPPLEMENTARY_APPLICATION_STATUS_CODES = SUPPLEMENTARY_APPLICATION_STATUS_CODES
removed

2024-04-01 23:40 UTC, weskubo-cgi commented on frontend/src/components/supp-allowances/TransportationAllowance.vue
> +<!-- eslint-disable vue/attribute-hyphenation -->
Let's remove for now and have a look at your settings. Also https://vuejs.org/guide/components/props.html#prop-passing-details.

2024-04-01 23:42 UTC, weskubo-cgi commented on frontend/src/utils/common.js
> +  return !(applicationStatusCode === STATUS_CODES.DRAFT || applicationStatusCode === STATUS_CODES.ACTION_REQUIRED)
I think keep it simple for now and maybe name accordingly (isSupplementaryApplicationLocked)? I'm not sure we'd have the same status codes to check anyways.

2024-04-02 00:05 UTC, weskubo-cgi approved these changes

2024-04-02 00:07 UTC, merged