Ofmcc 244 impersonate
bcgov/ecc-ofm pull request #22
Opened 2023-10-22 03:47 UTC by jgstorey

2023-10-22 17:01 UTC, weskubo-cgi requested changes

2023-10-22 19:27 UTC, jgstorey commented on frontend/src/styles/common.css
> +.cc-top-level-card {
Confirming complete.

2023-10-22 19:34 UTC, jgstorey commented on frontend/src/components/TheHeader.vue
>            </v-row>
The header user profile UI component dropdown (i.e. Home, Log Out) has been updated to include impersonate when a ministry user is signed in. This matches its accessible location in MyCSS. The bugs i was previous having around showing user profile icon have been resolved. If you still think we shouldn't show, I'll remove and re-add the 'Log Out' link and add an 'Impersonate Link'?

2023-10-22 20:25 UTC, jgstorey commented on frontend/src/styles/common.css
> +.cc-top-level-card {
![image](https://github.com/bcgov/ecc-ofm/assets/61481459/69811d7b-21ad-488a-bf02-abb945d9f1d4)

2023-10-22 20:27 UTC, jgstorey commented on frontend/src/views/HomeView.vue
> -          User
Are we sure its going to be that much of an issue for quick re-QA of small scree... screen is temporary.

2023-10-22 20:28 UTC, jgstorey commented on frontend/src/views/LoginView.vue
> +        <v-col cols="4" class="xs-12 lg-6 xl-2">
Confirming complete. i.e. http://localhost:8082/internal

2023-10-22 21:01 UTC, jgstorey commented on frontend/src/views/ImpersonateView.vue
> +.v-card {
Confirming fixed.

2023-10-22 21:04 UTC, jgstorey commented on frontend/src/views/ImpersonateView.vue
> +.v-card {
Confirming fixed.

2023-10-22 21:05 UTC, jgstorey commented on frontend/src/App.vue
> +
Confirming fixed.

2023-10-22 21:10 UTC, jgstorey commented on frontend/src/App.vue
> +    ...mapActions(useAuthStore, ['getJwtToken', 'logout']),
Confirmed fixed.

2023-10-22 21:15 UTC, jgstorey commented on frontend/src/components/TheHeader.vue
>            </v-row>
i.e
![image](https://github.com/bcgov/ecc-ofm/assets/61481459/a6aaa8ba-0986-4037-8e4e-a15749dfb9fd)

2023-10-22 21:15 UTC, weskubo-cgi commented on frontend/src/styles/common.css
> +.cc-top-level-card {
Just leave it then.

2023-10-22 21:16 UTC, weskubo-cgi commented on frontend/src/views/HomeView.vue
> -          User
Sure. It's temporary so let's just leave it.

2023-10-23 00:03 UTC, weskubo-cgi commented on frontend/src/components/TheHeader.vue
>            </v-row>
We can leave then if it helps with navigation/etc. We don't have a formal design anyways.

2023-10-23 05:10 UTC, weskubo-cgi approved these changes

2023-10-23 05:10 UTC, merged