Ofmcc 4329 show irreg expense
bcgov/ecc-ofm pull request #300
Opened 2024-07-23 00:27 UTC by jenbeckett

Notes: Still have some kinks to work out with Irreg Expense on the Applications Page - if MOD FA is not in Active status - then the Irreg Expenses don't show up 

Irregular Expense PDF notification doesn't generate yet on the Funding Tab

2024-07-24 17:00 UTC, weskubo-cgi requested changes

2024-07-24 20:40 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  [param('applicationId', 'URL param: [applicationId] is required').not().isEmpty()],
done

2024-07-24 20:40 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  [param('applicationId', 'URL param: [applicationId] is required').not().isEmpty()],
done

2024-07-24 20:40 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  [param('applicationId', 'URL param: [applicationId] is required').not().isEmpty()],
done

2024-07-24 21:04 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  [param('applicationId', 'URL param: [applicationId] is required').not().isEmpty()],
done

2024-07-24 21:04 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  [param('applicationId', 'URL param: [applicationId] is required').not().isEmpty()],
done

2024-07-24 21:04 UTC, jenbeckett commented on frontend/src/router/index.js
> +      path: '/approved-irregular-funding/:fundingGuid',
done

2024-07-24 21:04 UTC, jenbeckett commented on frontend/src/services/applicationService.js
> +      console.log(url)
done

2024-07-24 21:04 UTC, jenbeckett commented on frontend/src/views/funding/IrregularExpenseFunding.vue
> +  name: 'ApprovedFundingView',
done

2024-07-24 21:05 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  '/supplementary/:applicationId/supp',
done

2024-07-24 21:05 UTC, jenbeckett commented on backend/src/components/applications.js
> +    return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json(e.data ? e.data : e?.status)
done

2024-07-24 21:05 UTC, jenbeckett commented on frontend/src/views/applications/ApplicationsHistoryView.vue
> +      irregExpenses: [],
changed

2024-07-24 21:10 UTC, jenbeckett commented on frontend/src/router/index.js
> +      path: '/approved-funding/:fundingGuid',
done

2024-07-24 21:30 UTC, jenbeckett commented on frontend/src/views/funding/ViewApprovedFunding.vue
> +    <a style="text-decoration: none" :download="'Approval_Notification_' + application?.supplementaryReferenceNumber" :href="pdfDownloadLink">
done

2024-07-24 21:30 UTC, jenbeckett commented on frontend/src/views/funding/FundingView.vue
> +    <AppPDFViewer :pdfFile="pdfFile"></AppPDFViewer>
done

2024-07-24 21:30 UTC, jenbeckett commented on frontend/src/views/funding/IrregularExpenseFunding.vue
> +<style>
done

2024-07-24 21:31 UTC, jenbeckett commented on frontend/src/components/ui/AppPDFViewer.vue
> +<style>
done

2024-07-24 21:31 UTC, jenbeckett commented on backend/src/components/applications.js
> +    return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json(e.data ? e.data : e?.status)
done

2024-07-24 21:33 UTC, jenbeckett commented on backend/src/components/applications.js
> +async function getIrregularExpenseApplication(req, res) {
updated

2024-07-24 21:33 UTC, jenbeckett commented on backend/src/components/applications.js
> +  log.info('called')
done

2024-07-24 21:33 UTC, jenbeckett commented on backend/src/components/applications.js
> +    return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json(e.data ? e.data : e?.status)
done

2024-07-24 21:33 UTC, jenbeckett commented on backend/src/components/applications.js
> +  log.info('called')
done

2024-07-24 21:33 UTC, jenbeckett commented on backend/src/components/applications.js
> +    return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json(e.data ? e.data : e?.status)
done

2024-07-24 21:38 UTC, jenbeckett commented on frontend/src/services/applicationService.js
> +      const response = await ApiService.apiAxios.get(ApiRoutes.SUPPLEMENTARY_APPLICATIONS + '/' + supplementaryApplicationId + '/supp')
done

2024-07-24 21:44 UTC, jenbeckett commented on frontend/src/services/applicationService.js
> +      let url = `${ApiRoutes.APPLICATIONS}/irregularExpense/${applicationId}`
done

2024-07-24 21:48 UTC, jenbeckett commented on frontend/src/services/applicationService.js
> +  async getIrregularExpenseApplication(applicationId, filterQuery = undefined) {
good point, done

2024-07-24 22:25 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  [param('applicationId', 'URL param: [applicationId] is required').not().isEmpty()],
done

2024-07-24 23:13 UTC, jenbeckett commented on backend/src/components/applications.js
> +    ${buildAppsFilterQuery(req?.query, SupplementaryApplicationMappings, 'and statuscode ne 2')} )`
I think I have a hang on it now - I was having issues getting the 'and' to work nicely - but it should be fixed now

2024-07-24 23:13 UTC, jenbeckett commented on backend/src/routes/applications.js
> +  '/irregularExpense/:applicationId',
done

2024-07-25 22:47 UTC, weskubo-cgi approved these changes

2024-07-25 22:52 UTC, merged