Ofmcc 375 send documents to crm
bcgov/ecc-ofm pull request #50
Opened 2023-12-01 18:59 UTC by vietle-cgi

2023-12-01 20:04 UTC, weskubo-cgi requested changes

2023-12-01 22:11 UTC, vietle-cgi commented on frontend/src/stores/documents.js
> +    payload.append(`document[${index}]`, document.file[0])
this is updated

2023-12-01 22:11 UTC, vietle-cgi commented on frontend/src/stores/documents.js
> +  let payload = new FormData()
this is updated

2023-12-01 22:11 UTC, vietle-cgi commented on frontend/src/stores/documents.js
> +import { ApiRoutes } from '@/utils/constants'
I removed this document store and use documentService instead

2023-12-01 22:11 UTC, vietle-cgi commented on frontend/src/components/ui/AppDocumentUpload.vue
> +      },
this has been removed

2023-12-01 22:12 UTC, vietle-cgi commented on frontend/src/components/ui/AppDocumentUpload.vue
> +        <v-row v-for="(item, index) in documents" :key="index" no-gutters>
I updated the code to use uuid

2023-12-03 21:33 UTC, weskubo-cgi requested changes

2023-12-03 22:33 UTC, vietle-cgi commented on backend/src/components/utils.js
> +    log.error('postDocuments Error', e.response ? e.response.status : e.message)
I removed 1 of them

2023-12-03 22:33 UTC, vietle-cgi commented on frontend/src/services/documentService.js
> +    if (!isEmpty(documents)) {
I updated it to use early return pattern

2023-12-03 22:33 UTC, vietle-cgi commented on frontend/src/services/documentService.js
> +    if (document.file?.length > 0) {
I updated it to use early return pattern

2023-12-04 00:49 UTC, weskubo-cgi approved these changes

2023-12-04 02:34 UTC, merged