Ofmcc 729 update user
bcgov/ecc-ofm pull request #57
Opened 2023-12-12 06:15 UTC by jgstorey

Summary:

- contains partial implementation for OFMCC-729 (update user, stopped due to awaiting endpoint)
- contains complete implementation for OFMCC-202 (new user, required code from 729)
- Roles are retrieved dynamically (rolesMixin.js), I think we want to change constants roles to replace ids with textual name of role.

2023-12-12 21:53 UTC, weskubo-cgi requested changes

2023-12-12 22:15 UTC, jgstorey commented on frontend/src/mixins/alertMixin.js
>      setFailureAlert(message) {
Fixed.

2023-12-12 22:15 UTC, jgstorey commented on frontend/src/mixins/rolesMixin.js
> +    getRoleNameById(id) {
Fixed.

2023-12-12 22:16 UTC, jgstorey commented on frontend/src/components/settings/ManageUserDialog.vue
> +    <AppDialog v-model="isDisplayed" :title="addingNewUser ? 'Add new User' : 'Edit User'" :isLoading="isLoading" persistent max-width="35%" @close="closeManageUserDialog">
Fixed. Mock up says 'Add new user', my bad.

2023-12-12 22:18 UTC, jgstorey commented on frontend/src/components/settings/ManageUserDialog.vue
> +    <AppDialog v-model="isDisplayed" :title="addingNewUser ? 'Add new User' : 'Edit User'" :isLoading="isLoading" persistent max-width="35%" @close="closeManageUserDialog">
I like that approach more... updated.

2023-12-12 22:19 UTC, jgstorey commented on frontend/src/components/settings/ManageUserDialog.vue
> +    <AppDialog v-model="isDisplayed" :title="addingNewUser ? 'Add new User' : 'Edit User'" :isLoading="isLoading" persistent max-width="35%" @close="closeManageUserDialog">
Understood this for going forward, your changes addressing this merged into branch.

2023-12-12 23:44 UTC, jgstorey commented on frontend/src/components/settings/ManageUserDialog.vue
> +          <v-row no-gutters :class="{ 'mt-5': true, 'mb-6': !addingNewUser }">
Reason using mt and mb are adding space for when bceid input is editable or static. Without it things don't line up. Played with it awhile and came back to same place.

2023-12-13 00:58 UTC, weskubo-cgi approved these changes

2023-12-13 01:01 UTC, merged