Auth and jwt integration with front/backend.
bcgov/ecc-ofm pull request #9
Opened 2023-09-18 23:10 UTC by jgstorey

2023-09-20 23:24 UTC, jgstorey commented
@weskubo-cgi, updates include port number change in vite.config.js (MyCCS used 8082 so made it same), change to whatever you want. Updated header UI to look like MyCCS.

2023-09-21 17:28 UTC, weskubo-cgi requested changes

2023-09-21 18:41 UTC, jgstorey commented on frontend/src/components/Header.vue
> +      <h3>{{ secureAppTitle }}</h3>
Fixed

2023-09-21 18:41 UTC, jgstorey commented on frontend/src/router/index.js
> +    const apStore = useAppStore();
Fixed

2023-09-21 18:43 UTC, weskubo-cgi approved these changes

2023-09-21 18:50 UTC, merged